# Generated by Django 6.0.7 on 2026-07-10 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='district',
            new_name='districts',
        ),
    ]
