# Generated by Django 6.0.7 on 2026-07-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0003_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='districts',
            field=models.ManyToManyField(related_name='district_posts', to='neighborhood.district'),
        ),
    ]
